# Generated by Django 5.2.11 on 2026-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetask",
            name="worker_id",
            field=models.SmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Celery worker that handled this send.",
                null=True,
            ),
        ),
    ]
