# Generated by Django 5.2.11 on 2026-02-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_add_worker_id_to_messagetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetask",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="messagetask",
            name="error_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rate_limited", "Rate Limited"),
                    ("session_expired", "Session Expired"),
                    ("group_not_found", "Group Not Found"),
                    ("timeout", "Timeout"),
                    ("send_failed", "Send Failed"),
                    ("bot_detected", "Bot Detected"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="messagetask",
            name="last_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagetask",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="is_healthy",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Auto-set False after N consecutive failures.",
            ),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="last_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="total_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="total_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MessageAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "error_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rate_limited", "Rate Limited"),
                            ("session_expired", "Session Expired"),
                            ("group_not_found", "Group Not Found"),
                            ("timeout", "Timeout"),
                            ("send_failed", "Send Failed"),
                            ("bot_detected", "Bot Detected"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "screenshot_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="campaigns.messagetask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attempt",
                "verbose_name_plural": "Message Attempts",
                "ordering": ["started_at"],
            },
        ),
    ]
