# Generated by Django 5.2.11 on 2026-02-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0003_messagetask_attempt_count_messagetask_error_category_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable community name.", max_length=255
                    ),
                ),
                (
                    "community_jid",
                    models.CharField(
                        db_index=True,
                        help_text="Community search name used in WhatsApp Web chat list.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive community excludes all its sub-groups from broadcasts.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "WhatsApp Community",
                "verbose_name_plural": "WhatsApp Communities",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="is_announcement_channel",
            field=models.BooleanField(
                default=False,
                help_text="True for the community Announcement Channel (admin-only posting).",
            ),
        ),
        migrations.AddField(
            model_name="whatsappgroup",
            name="community",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent community if this group is a community sub-group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subgroups",
                to="campaigns.whatsappcommunity",
            ),
        ),
    ]
