# Generated by Django 5.2.11 on 2026-03-04 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_whatsappcommunity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Display label, e.g. "Admin 1".', max_length=50
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number for identification (e.g. +91XXXXXXXXXX).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive admin is excluded from broadcast assignment.",
                    ),
                ),
                (
                    "sessions_per_admin",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Browser sessions (linked devices) for this admin (1–4).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "warm_up_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this number started its warm-up phase.",
                        null=True,
                    ),
                ),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admin Account",
                "verbose_name_plural": "Admin Accounts",
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="messagetask",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin account that sent (or will send) this message.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_tasks",
                to="campaigns.adminaccount",
            ),
        ),
    ]
