# Generated by Django 5.2.11 on 2026-03-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_adminaccount_skip_warmup"),
        ("scraper", "0002_add_image_url_to_scrapedarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastevent",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcasts",
                to="scraper.scrapedarticle",
            ),
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal label for this campaign.", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Message body. Supports WhatsApp formatting (*bold*, _italic_, ~strikethrough~)."
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all_groups", "All Groups"),
                            ("all_communities", "All Communities"),
                            ("specific", "Specific"),
                        ],
                        db_index=True,
                        default="all_groups",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_communities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Used when target_type is SPECIFIC.",
                        related_name="advertisements",
                        to="campaigns.whatsappcommunity",
                    ),
                ),
                (
                    "target_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Used when target_type is SPECIFIC.",
                        related_name="advertisements",
                        to="campaigns.whatsappgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="broadcastevent",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcasts",
                to="campaigns.advertisement",
            ),
        ),
        migrations.CreateModel(
            name="MediaAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="advertisements/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_attachments",
                        to="campaigns.advertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Attachment",
                "verbose_name_plural": "Media Attachments",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
