# Generated by Django 5.2.11 on 2026-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_advertisement_title_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="package_days",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Total working days in this advertising package."
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="preferred_time",
            field=models.TimeField(
                blank=True,
                help_text="Advertiser's preferred send time (informational only).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
