# Generated by Django 5.2.11 on 2026-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_advertisement_packages"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_text",
                    models.TextField(
                        help_text="WhatsApp-formatted message. Available placeholders: {news.title}, {news.description}, {news.url}, {news.source}, {news.published_at}, {news.time}."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "ordering": ["-updated_at"],
            },
        ),
    ]
