# Generated by Django 5.2.11 on 2026-02-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("active", "Active"),
                            ("idle", "Idle"),
                            ("error", "Error"),
                            ("offline", "Offline"),
                        ],
                        default="starting",
                        max_length=20,
                    ),
                ),
                (
                    "browser_status",
                    models.CharField(
                        choices=[
                            ("launching", "Launching"),
                            ("logged_in", "Logged In"),
                            ("qr_required", "QR Required"),
                            ("banned", "Banned"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                (
                    "current_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "current_group",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Worker Session",
                "verbose_name_plural": "Worker Sessions",
                "ordering": ["worker_id"],
            },
        ),
        migrations.CreateModel(
            name="WorkerSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("logged_in", "Logged In"),
                            ("qr_detected", "QR Detected"),
                            ("error", "Error"),
                            ("ban_detected", "Ban Detected"),
                            ("heartbeat", "Heartbeat"),
                            ("task_started", "Task Started"),
                            ("task_completed", "Task Completed"),
                            ("task_failed", "Task Failed"),
                            ("shutdown", "Shutdown"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="automation.workersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Session Log",
                "verbose_name_plural": "Worker Session Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
