# Generated by Django 5.2.11 on 2026-03-04 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
        ("campaigns", "0005_add_admin_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="workersession",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin account this worker is bound to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker_sessions",
                to="campaigns.adminaccount",
            ),
        ),
    ]
