import { MigrationInterface, QueryRunner } from "typeorm";

export class CompleteSchemaForPostgres1784887919922 implements MigrationInterface {
    name = 'CompleteSchemaForPostgres1784887919922'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "wa_sessions" ("session_name" text NOT NULL, "data" bytea NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8661e1914cedbd611c3a08fbf2b" PRIMARY KEY ("session_name"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "worker_sessions" ("id" SERIAL NOT NULL, "adminId" integer NOT NULL, "workerId" character varying(100) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'offline', "browserStatus" character varying(20) NOT NULL DEFAULT 'unknown', "lastHeartbeatAt" TIMESTAMP, "totalSent" integer NOT NULL DEFAULT '0', "totalFailed" integer NOT NULL DEFAULT '0', "currentGroupId" character varying(255), "lastError" text, "openwaSessionId" character varying(100), "openwaSessionStatus" character varying(20), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ce9e1860f7b1383573540b55273" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_d40391f72378dc23d174c904e1" ON "worker_sessions" ("workerId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "worker_session_logs" ("id" SERIAL NOT NULL, "workerSessionId" integer NOT NULL, "event" character varying(50) NOT NULL, "detail" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_03c6b930ec3c902b21a1648a3ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6e53cacd83019b5ab72d430c2b" ON "worker_session_logs" ("workerSessionId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "whatsapp_communities" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "communityJid" character varying(255) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "totalSent" integer NOT NULL DEFAULT '0', "totalFailed" integer NOT NULL DEFAULT '0', "lastSentAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_41ec36b97e9663a7d22ce47bc7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ba58faed82585d2f0065aa07cc" ON "whatsapp_communities" ("communityJid") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "whatsapp_groups" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "groupJid" character varying(255) NOT NULL, "openwaGroupId" character varying(255), "isAnnouncementChannel" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "isTargeted" boolean NOT NULL DEFAULT false, "totalSent" integer NOT NULL DEFAULT '0', "totalFailed" integer NOT NULL DEFAULT '0', "consecutiveFailures" integer NOT NULL DEFAULT '0', "isHealthy" boolean NOT NULL DEFAULT true, "lastSentAt" TIMESTAMP, "lastFailureAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "communityId" integer, CONSTRAINT "PK_372deb1c66cb231b05ba757e6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_54ab47ae6d8385e6c64e567a1f" ON "whatsapp_groups" ("groupJid") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "whatsapp_group_members" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "adminId" integer NOT NULL, "sessionId" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_79673131ddca51a989aebe96bc7" UNIQUE ("groupId", "adminId"), CONSTRAINT "PK_38a29d078366277a2131f1366c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_6bda793fa7c96c4074764fc8c5" ON "whatsapp_group_members" ("groupId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "wa_users" ("id" SERIAL NOT NULL, "username" character varying(100) NOT NULL, "passwordHash" character varying(255) NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'admin', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b76e2c6d7467e00a390f5f83bcf" UNIQUE ("username"), CONSTRAINT "PK_853e84939c32696f27475470088" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "scraper_activity_log" ("id" SERIAL NOT NULL, "url" character varying(1024) NOT NULL, "articlesFound" integer NOT NULL DEFAULT '0', "articlesNew" integer NOT NULL DEFAULT '0', "articlesSkipped" integer NOT NULL DEFAULT '0', "articlesFailed" integer NOT NULL DEFAULT '0', "listingChanged" boolean NOT NULL DEFAULT false, "errors" text, "durationMs" integer NOT NULL DEFAULT '0', "checkedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_65bfa04663c93c5883593da4a5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "scraped_articles" ("id" SERIAL NOT NULL, "url" character varying(1024) NOT NULL, "title" text, "description" text, "body" text, "imageUrl" character varying(1024), "bulletPoints" text, "sourceName" character varying(255), "publishedAt" TIMESTAMP, "contentHash" character varying(64), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bd33847a79774b4e054cd9e2ea9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "runtime_settings" ("id" SERIAL NOT NULL, "key" character varying(255) NOT NULL, "value" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b63b36eb3b51c63737f1d17c8b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_e12c6dba147684ac546ed82ef3" ON "runtime_settings" ("key") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "message_templates" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "templateText" text NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ac2bd9635be662d183f314947d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "broadcast_events" ("id" SERIAL NOT NULL, "advertisementId" integer, "messageText" text, "editHistory" text, "status" character varying(20) NOT NULL DEFAULT 'pending', "totalMessages" integer NOT NULL DEFAULT '0', "sentCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "articleId" integer, CONSTRAINT "PK_c2733f1bfb23bfddd29dca12357" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "admin_accounts" ("id" SERIAL NOT NULL, "label" character varying(255) NOT NULL, "phoneNumber" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "sessionsPerAdmin" integer NOT NULL DEFAULT '1', "warmUpStartedAt" TIMESTAMP, "skipWarmup" boolean NOT NULL DEFAULT false, "warmUpDay" integer NOT NULL DEFAULT '0', "totalSent" integer NOT NULL DEFAULT '0', "totalFailed" integer NOT NULL DEFAULT '0', "lastSentAt" TIMESTAMP, "openwaSessionId" character varying(255), "isSuperAdmin" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3cbba0b513d0402c1559d82b46c" UNIQUE ("phoneNumber"), CONSTRAINT "PK_79fb3604ed15538685183d8df5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "message_tasks" ("id" SERIAL NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "workerId" character varying(100), "waMessageId" character varying(100), "errorMessage" text, "errorCategory" character varying(50), "attemptCount" integer NOT NULL DEFAULT '0', "maxAttempts" integer NOT NULL DEFAULT '3', "lastAttemptAt" TIMESTAMP, "nextRetryAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "broadcastId" integer, "groupId" integer, "adminId" integer, CONSTRAINT "PK_fbe0c070b3911687a23a7f3d2a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_d0fffc81a73be32d1018622a99" ON "message_tasks" ("broadcastId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_b052d517388ea08f7188ea70ae" ON "message_tasks" ("groupId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "message_attempts" ("id" SERIAL NOT NULL, "attemptNumber" integer NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "errorCategory" character varying(50), "errorMessage" text, "responseTimeMs" integer, "screenshotPath" character varying(1024), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "messageTaskId" integer, CONSTRAINT "PK_32fa8831d7474e6547fb7f87fd4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "advertisements" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "body" text, "targetType" character varying(30) NOT NULL DEFAULT 'all_groups', "status" character varying(20) NOT NULL DEFAULT 'draft', "packageDays" integer NOT NULL DEFAULT '1', "daysUsed" integer NOT NULL DEFAULT '0', "preferredTime" character varying(20), "nextScheduledAt" TIMESTAMP, "lastDispatchedAt" TIMESTAMP, "totalSent" integer NOT NULL DEFAULT '0', "totalFailed" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4818a08332624787e5b2bf82302" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "media_attachments" ("id" SERIAL NOT NULL, "filePath" character varying(255) NOT NULL, "mediaType" character varying(50) NOT NULL, "originalFilename" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "advertisementId" integer, CONSTRAINT "PK_c0180c139bb436a433605c069ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "article_hashes" ("id" SERIAL NOT NULL, "url" character varying(1024) NOT NULL, "contentHash" character varying(64) NOT NULL, "checkedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e2a7a08a77918e20b0a9a4caf54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_2c590634c1aa086cd6d06b05d1" ON "article_hashes" ("url") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "admin_sessions" ("id" SERIAL NOT NULL, "adminId" integer NOT NULL, "sessionIndex" integer NOT NULL DEFAULT '0', "openwaSessionId" character varying(255) NOT NULL, "openwaSessionStatus" character varying(20) NOT NULL DEFAULT 'created', "phone" character varying(50), "pushName" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_38bb553c2372215d48de2306c5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS "IDX_084e4ceb0c7b6c442ddf4081e4" ON "admin_sessions" ("openwaSessionId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "advertisement_groups" ("advertisementsId" integer NOT NULL, "whatsappGroupsId" integer NOT NULL, CONSTRAINT "PK_00f0f00f58b9013ce25646551a8" PRIMARY KEY ("advertisementsId", "whatsappGroupsId"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_680131a1cbc5f0c66f349a9639" ON "advertisement_groups" ("advertisementsId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_eef07b05f10eab3e3ace4a6301" ON "advertisement_groups" ("whatsappGroupsId") `);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "advertisement_communities" ("advertisementsId" integer NOT NULL, "whatsappCommunitiesId" integer NOT NULL, CONSTRAINT "PK_14c12066c2cd94bcf3a29ad799e" PRIMARY KEY ("advertisementsId", "whatsappCommunitiesId"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e034aba0bfe35bfc77c7e3391e" ON "advertisement_communities" ("advertisementsId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_8eb876d5d3c0798a233a58e2ba" ON "advertisement_communities" ("whatsappCommunitiesId") `);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_d209715bb62b12255e825580af6"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_pkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "config"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "config" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "webhooks_pkey"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "sessionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "events"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "events" jsonb NOT NULL DEFAULT '["message.received"]'`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "headers"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "headers" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "messages_pkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP CONSTRAINT "message_batches_pkey"`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD CONSTRAINT "PK_e69bcf640f4e7dd1350064b2e8b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "messages"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "messages" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "options"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "options" jsonb`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "progress"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "progress" jsonb`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "results"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "results" jsonb`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "api_keys_pkey"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_pkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "whatsapp_groups" ADD CONSTRAINT "FK_6803ff8de698ddf440dd973c20d" FOREIGN KEY ("communityId") REFERENCES "whatsapp_communities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "broadcast_events" ADD CONSTRAINT "FK_611d249af7a928b229eccdd3eff" FOREIGN KEY ("articleId") REFERENCES "scraped_articles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_tasks" ADD CONSTRAINT "FK_d0fffc81a73be32d1018622a99b" FOREIGN KEY ("broadcastId") REFERENCES "broadcast_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_tasks" ADD CONSTRAINT "FK_b052d517388ea08f7188ea70ae8" FOREIGN KEY ("groupId") REFERENCES "whatsapp_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_tasks" ADD CONSTRAINT "FK_23f7f0bec5ee24125634765cf9b" FOREIGN KEY ("adminId") REFERENCES "admin_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_attempts" ADD CONSTRAINT "FK_f47d7c180606d845af197f60bcd" FOREIGN KEY ("messageTaskId") REFERENCES "message_tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_attachments" ADD CONSTRAINT "FK_da4164a3ed463ed521150554dca" FOREIGN KEY ("advertisementId") REFERENCES "advertisements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "advertisement_groups" ADD CONSTRAINT "FK_680131a1cbc5f0c66f349a96397" FOREIGN KEY ("advertisementsId") REFERENCES "advertisements"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "advertisement_groups" ADD CONSTRAINT "FK_eef07b05f10eab3e3ace4a63012" FOREIGN KEY ("whatsappGroupsId") REFERENCES "whatsapp_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "advertisement_communities" ADD CONSTRAINT "FK_e034aba0bfe35bfc77c7e3391e2" FOREIGN KEY ("advertisementsId") REFERENCES "advertisements"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "advertisement_communities" ADD CONSTRAINT "FK_8eb876d5d3c0798a233a58e2ba8" FOREIGN KEY ("whatsappCommunitiesId") REFERENCES "whatsapp_communities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "advertisement_communities" DROP CONSTRAINT "FK_8eb876d5d3c0798a233a58e2ba8"`);
        await queryRunner.query(`ALTER TABLE "advertisement_communities" DROP CONSTRAINT "FK_e034aba0bfe35bfc77c7e3391e2"`);
        await queryRunner.query(`ALTER TABLE "advertisement_groups" DROP CONSTRAINT "FK_eef07b05f10eab3e3ace4a63012"`);
        await queryRunner.query(`ALTER TABLE "advertisement_groups" DROP CONSTRAINT "FK_680131a1cbc5f0c66f349a96397"`);
        await queryRunner.query(`ALTER TABLE "media_attachments" DROP CONSTRAINT "FK_da4164a3ed463ed521150554dca"`);
        await queryRunner.query(`ALTER TABLE "message_attempts" DROP CONSTRAINT "FK_f47d7c180606d845af197f60bcd"`);
        await queryRunner.query(`ALTER TABLE "message_tasks" DROP CONSTRAINT "FK_23f7f0bec5ee24125634765cf9b"`);
        await queryRunner.query(`ALTER TABLE "message_tasks" DROP CONSTRAINT "FK_b052d517388ea08f7188ea70ae8"`);
        await queryRunner.query(`ALTER TABLE "message_tasks" DROP CONSTRAINT "FK_d0fffc81a73be32d1018622a99b"`);
        await queryRunner.query(`ALTER TABLE "broadcast_events" DROP CONSTRAINT "FK_611d249af7a928b229eccdd3eff"`);
        await queryRunner.query(`ALTER TABLE "whatsapp_groups" DROP CONSTRAINT "FK_6803ff8de698ddf440dd973c20d"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_d209715bb62b12255e825580af6"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "PK_1bb179d048bbc581caa3b013439"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "id" character varying NOT NULL DEFAULT (gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD "id" character varying NOT NULL DEFAULT (gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "results"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "results" text`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "progress"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "progress" text`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "options"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "options" text`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "messages"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "messages" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP CONSTRAINT "PK_e69bcf640f4e7dd1350064b2e8b"`);
        await queryRunner.query(`ALTER TABLE "message_batches" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD "id" character varying NOT NULL DEFAULT (gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "message_batches" ADD CONSTRAINT "message_batches_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "metadata" text`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "PK_18325f38ae6de43878487eff986"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "id" character varying NOT NULL DEFAULT (gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "headers"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "headers" text NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "events"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "events" text NOT NULL DEFAULT '["message.received"]'`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "sessionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD "id" character varying NOT NULL DEFAULT (gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "webhooks_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "config"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "config" text NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "PK_3238ef96f18b355b671619111bc"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "id" character varying NOT NULL DEFAULT (gen_random_uuid())`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_d209715bb62b12255e825580af6" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8eb876d5d3c0798a233a58e2ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e034aba0bfe35bfc77c7e3391e"`);
        await queryRunner.query(`DROP TABLE "advertisement_communities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eef07b05f10eab3e3ace4a6301"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_680131a1cbc5f0c66f349a9639"`);
        await queryRunner.query(`DROP TABLE "advertisement_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_084e4ceb0c7b6c442ddf4081e4"`);
        await queryRunner.query(`DROP TABLE "admin_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c590634c1aa086cd6d06b05d1"`);
        await queryRunner.query(`DROP TABLE "article_hashes"`);
        await queryRunner.query(`DROP TABLE "media_attachments"`);
        await queryRunner.query(`DROP TABLE "advertisements"`);
        await queryRunner.query(`DROP TABLE "message_attempts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b052d517388ea08f7188ea70ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0fffc81a73be32d1018622a99"`);
        await queryRunner.query(`DROP TABLE "message_tasks"`);
        await queryRunner.query(`DROP TABLE "admin_accounts"`);
        await queryRunner.query(`DROP TABLE "broadcast_events"`);
        await queryRunner.query(`DROP TABLE "message_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12c6dba147684ac546ed82ef3"`);
        await queryRunner.query(`DROP TABLE "runtime_settings"`);
        await queryRunner.query(`DROP TABLE "scraped_articles"`);
        await queryRunner.query(`DROP TABLE "scraper_activity_log"`);
        await queryRunner.query(`DROP TABLE "wa_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bda793fa7c96c4074764fc8c5"`);
        await queryRunner.query(`DROP TABLE "whatsapp_group_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54ab47ae6d8385e6c64e567a1f"`);
        await queryRunner.query(`DROP TABLE "whatsapp_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba58faed82585d2f0065aa07cc"`);
        await queryRunner.query(`DROP TABLE "whatsapp_communities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e53cacd83019b5ab72d430c2b"`);
        await queryRunner.query(`DROP TABLE "worker_session_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d40391f72378dc23d174c904e1"`);
        await queryRunner.query(`DROP TABLE "worker_sessions"`);
        await queryRunner.query(`DROP TABLE "wa_sessions"`);
    }

}
