# Generated by Django 5.2.11 on 2026-02-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("checked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article Hash",
                "verbose_name_plural": "Article Hashes",
            },
        ),
        migrations.CreateModel(
            name="ScrapedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("body", models.TextField(help_text="Raw extracted text content.")),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scraped Article",
                "verbose_name_plural": "Scraped Articles",
                "ordering": ["-created_at"],
            },
        ),
    ]
