# Generated by Django 5.2.11 on 2026-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedarticle",
            name="image_url",
            field=models.URLField(
                blank=True, default="", help_text="Poster/tile image URL."
            ),
        ),
    ]
