# Generated by Django 5.2.11 on 2026-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_add_image_url_to_scrapedarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedarticle",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw article description / summary — used as {news.description} in templates.",
            ),
        ),
        migrations.AddField(
            model_name="scrapedarticle",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the article was published on the source site.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scrapedarticle",
            name="source_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the originating news source.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="scrapedarticle",
            name="body",
            field=models.TextField(
                help_text="Pre-formatted WhatsApp message (legacy fallback when no template is set)."
            ),
        ),
    ]
